---
# tasks file for ansible-role-docker
- name: install depends package
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: install docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    chdir: /etc/yum.repos.d
    creates: docker-ce.repo

- name: install docker package
  yum:
    name:
      - docker-ce

- name: start docker service
  service:
    name: docker
    state: started
    enabled: yes
  when: start_skip is undefined

- name: set swarm manager hostnames
  set_fact:
    docker_swarm_manager_hostnames: "{{ ansible_play_hosts[0:docker_swarm_managers] }}"
  when: docker_swarm_managers > 0

- include_tasks: swarm_cluster.yml
  when: docker_swarm_manager_hostnames is defined
